name: ASP.NET Core CD

on:
  workflow_run:
    workflows:
      - ASP.NET Core CI
    types:
      - completed

jobs:
  deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0

    - name: Publish
      shell: cmd
      run: |
        dotnet publish -c Release -o .\publish

    - name: Deploy Locally
      shell: cmd
      run: |
        iisreset /stop
        xcopy /s /y .\publish\* c:\inetpub\wwwroot\ClientServerSimpleApp1\
        iisreset /start


  
