name: ASP.NET Core CD

on:
  workflow_run:
    workflows:
      - ASP.NET Core CI
    types:
      - completed

jobs:
  deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0

    - name: Publish
      run: dotnet publish ClientServerSimpleApp1/ClientServerSimpleApp1.csproj -c Release -o ./publish

    - name: Deploy Locally
      shell: cmd
      run: xcopy ./publish C:\inetpub\wwwroot\ClientServerSimpleApp2 /E /I /Y


  
